<?php
/*================================================================================
    OMOP - Cloud Research Lab

    Observational Medical Outcomes Partnership
    24 Jan 2011

    Contains view template for displaying the Run Results info

    (C)2009-2011 Foundation for the National Institutes of Health (FNIH)

    Licensed under the Apache License, Version 2.0 (the "License"); you may not
    use this file except in compliance with the License. You may obtain a copy
    of the License at http://omop.fnih.org/publiclicense.

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. Any
    redistributions of this work or any derivative work or modification based on
    this work should be accompanied by the following source attribution: "This
    work is based on work by the Observational Medical Outcomes Partnership
    (OMOP) and used under license from the FNIH at
    http://omop.fnih.org/publiclicense.

    Any scientific publication that is based on this work should include a
    reference to http://omop.fnih.org.

================================================================================*/
?>
<?php $this->emptyDate = htmlspecialchars($this->emptyDate); ?>
<?php $this->headLink()->appendStylesheet('/css/jquery/smoothness/jquery-ui-1.7.3.custom.css')?>
<?php echo $this->partial('_javascript_autoload.phtml', array('page' => 'result_s3'))?>
<?php $this->headScript()->appendFile('/js/jquery-ui-1.7.3.custom.min.js')?>
<?php // $this->headScript()->appendFile('/js/s3results.js')?>
<?php $this->headScript()->captureStart();?>


<?php $this->headScript()->captureEnd();?>

<style type="tetext/css">
    #container div.list table tbody td {
        white-space: nowrap;
    }
</style>

<div class="clear"></div>
<div class="list">
    <?=$this->partial('_round_corners.phtml');?>
    <div style="padding-left:15px;padding-top:20px;">
        <label for="idExperiment">Select Experiment:</label>
        <?php if(count($this->experiments)): ?>
        <select id="idExperiment" name="experiment" onchange="window.location = '<?php echo $this->baseUrl();?>/s3results/list/experiment/' + $(this).val()">
            <option value="0" selected="selected">--Not selected--</option>
            <?php foreach($this->experiments as $experiment): ?>
            <option value="<?=$experiment['EXPERIMENT_ID']?>" <?php echo $experiment['EXPERIMENT_ID'] == $this->experiment ? 'selected="selected"' : ''; ?>><?=$experiment['EXPERIMENT_NAME']?></option>
            <?php endforeach; ?>
        </select>
        <?php else: ?>
        <p><em>There are no available experiments.</em></p>
        <?php endif;?>
    </div>
    <div style="overflow-x:scroll;width:1120px;margin:15px 0 15px 10px;">
        <table cellspacing="0" cellpadding="0" border="0" style="margin:0;">
            <thead>
                <tr>
                    <th>Datasets</th>
                    <th colspan="<?=count($this->methods);?>" style="text-align: center">Methods</th>
                </tr>
                <tr>
                    <th>&nbsp;</th>
                    <?php foreach ($this->methods as $methodName): ?>
                    <th><?=$methodName ?></th>
                    <?php endforeach; ?>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->datasets as $dataset): ?>
                <?=$this->partial('s3results/_method_row.phtml', array('data'=>$this->methodRuns,
                                                                       'methods'=>$this->methods,
                                                                       'dataset'=>$dataset,
                                                                       'timeFormat'=>$this->timeFormat,
                                                                       'emptyDate'=>$this->emptyDate));?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
<div id="ajax-loader-container" style="display: none;" title="Loading...">
    <div id="ajax-loader"><img src="/images/ajax-loader.gif" /></div>
</div>
<div id="runs-list" style="display: none;" title="Runs"></div>
<div id="run-details" style="display: none;" title="Run details"></div>