<?php
/*================================================================================
    OMOP - Cloud Research Lab

    Observational Medical Outcomes Partnership
    15 December 2009

    Contains view template for displaying 'fieldset' element submenu and
    rounding its corners

    (C)2009 Foundation for the National Institutes of Health (FNIH)

    Licensed under the Apache License, Version 2.0 (the "License"); you may not
    use this file except in compliance with the License. You may obtain a copy
    of the License at http://omop.fnih.org/publiclicense.

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. Any
    redistributions of this work or any derivative work or modification based on
    this work should be accompanied by the following source attribution: "This
    work is based on work by the Observational Medical Outcomes Partnership
    (OMOP) and used under license from the FNIH at
    http://omop.fnih.org/publiclicense.

    Any scientific publication that is based on this work should include a
    reference to http://omop.fnih.org.

================================================================================*/
?>
<?php if (!isset($this->noCorners) || !$this->noCorners):?>
<img class="top_left" src="/images/top_left.gif" width="11" height="11" alt="" />
<img class="top_right" src="/images/top_right.gif" width="11" height="11" alt="" />
<img class="bottom_left" src="/images/bottom_left.gif" width="11" height="11" alt="" />
<img class="bottom_right" src="/images/bottom_right.gif" width="11" height="11" alt="" />
<?php endif; ?>
<?php if (isset($this->title)):?>
<h2><?php echo $this->title;?></h2>
<?php else: //getting info from Bootstrap?>
<?php
    $page = $this->navigation()->findOneBy('active', true);
    
    if ($page == null) {
    	// If we don't have page registered in the Bootstrap, then we just don't set any page title.
    	$title = '';
    } else {
	    $siblings = $page->getParent()->pages;
	    if ($siblings == null) {
	        $title = $page->title;
        } else {
	        $title_parts = array();
	        foreach ($siblings as $s) {
	            if ($s->tab) {
	                if ($s->isActive()) {
	                    $title_parts[] = $s->title;
	                } else {
	                    // TODO maybe replace with checking instance of which class is this page (URI or MVC)
	                    $url = $s->uri ? 
                               $s->uri
                               : $this->url(array('controller'=>$s->controller, 
                                                  'action'=>$s->action), 'default', 'true');
	                    $title_parts[] = "<a title=\"{$s->title}\" href=\"$url\">{$s->title}</a>";
	                }
	            }
	        }
            if (empty($title_parts)) {
                $title = $page->title;
            } else {
                $title = implode('&nbsp;|&nbsp;', $title_parts);
            }
	    }
    }
?>
<h2><?php echo $title;?></h2>
<?php endif?>