<div class="list">
    <?php echo $this->partial('_round_corners.phtml')?>
    <table cellspacing="0" cellpadding="0" border="0">
	<thead>
	<tr>
        <?php
            $columns = array(
               array('column_name' => 'User Login'),
               array('column_name' => 'Method Abbr'),
               array('column_name' => 'Upload Date'),
               array('column_name' => 'Filename'),
            );
            echo $this->partialLoop('_column_header.phtml', $columns);
        ?>
	</tr>
	</thead>
	<tfoot>
        <tr>
            <th colspan="7">
                <?php echo $this->paginator ?>
            </th>
        </tr>
	</tfoot>

    <tbody>
        <?php foreach($this->paginator as $entry): ?>
        <tr>
			<td><a href="<?php echo PageRouter::build('edit_user', $entry['user_id'])?>"><?php echo $this->escape($entry['user_login_id'])?></a></td>
			<td><a href="<?php echo $this->url(array('controller' => 'method', 'action' => 'analysis', 'id' => $entry['method_id']), 'default', true)?>"><?php echo $this->escape($entry['method_abbr'])?></a></td>
            <td><?php echo $this->dateFormat($this->escape($entry['upload_date']))?></td>
			<td><?php echo $this->escape($entry['filename'])?></td>
        </tr>
		<?php endforeach ?>
	</tbody>
    </table>
</div>