<div class="list">
    <?php echo $this->partial('_round_corners.phtml')?>
    <table cellspacing="0" cellpadding="0" border="0">
	<thead>
	<tr>
        <?php
            $columns = array(
               array('column_name' => 'Error Date'),
               array('column_name' => 'User ID'),
               array('column_name' => 'Remote IP'),
               array('column_name' => 'Description'),
               array('column_name' => 'Details'),
            );
            echo $this->partialLoop('_column_header.phtml', $columns);
        ?>
	</tr>
	</thead>
	<tfoot>
        <tr>
            <th colspan="7">
                <?php echo $this->paginator ?>
            </th>
        </tr>
	</tfoot>

    <tbody>
        <?php foreach($this->paginator as $entry): ?>
        <tr>
			<td><?php echo $this->dateFormat($this->escape($entry['date']))?></td>
			<td><?php echo $this->escape($entry['user'])?></td>
			<td><?php echo $this->escape($entry['ip'])?></td>
			<td><?php echo $this->truncate($this->escape($entry['description']))?></td>
			<td><a href="<?php echo $this->url(array('controller' => 'event', 'action' => 'exception', 'id' => $entry['id']))?>">Details</a></td>
        </tr>
		<? endforeach ?>
	</tbody>
    </table>
</div>