<div class="list">
    <?php echo $this->partial('_round_corners.phtml', array('title' => 'Images List'))?>
    <table cellspacing="0" cellpadding="0" border="0">
	<thead>
	<tr>
        <?php
            $columns = array(
               array('column_name' => 'Type', 'sortable' => false),
               array('column_name' => 'Sort Order', 'sortable' => false),
               array('column_name' => 'Default Flag', 'sortable' => false),
               array('column_name' => 'AMI', 'sortable' => false),
               array('column_name' => 'Platform', 'sortable' => false),
               array('column_name' => 'EBS', 'sortable' => false),
               array('column_name' => 'Cluster', 'sortable' => false),
               array('column_name' => 'GPU', 'sortable' => false),
               array('column_name' => 'OS Family', 'sortable' => false),
               array('column_name' => 'Actions')
            );
            echo $this->partialLoop('_column_header.phtml', $columns);
        ?>
	</tr>
	</thead>
	<tfoot>
        <tr>
            <th colspan="10">
                <?php echo $this->paginator ?>
            </th>
        </tr>
        <tr>
	    <th colspan="10">
	    <input onmouseover="this.style.backgroundPosition='bottom';" onmouseout="this.style.backgroundPosition='top';"
            id="button_new_dataset" class="button_105"
            type="button" value="Add Image" onclick="window.location='<?php echo $this->url(array('action' => 'add'))?>'" />
            </th>
        </tr>
	</tfoot>

    <tbody>
        <?php foreach($this->paginator as $k => $entry): ?>
        <tr>
			<td><a href="<?php echo $this->url(array('action' => 'edit', 'id' => $entry['id']))?>"><?php echo $this->escape($entry['type'])?></a></td>
			<td class="right">
                <?php echo $this->escape($entry['sortOrder'])?>
                <a href="<?php if ($k != 0) echo $this->url(array('action' => 'move-up', 'id' => $entry['id'])); else '#' ?>">
                    <img src="/images/moveup.png" alt="Move Up"
                         <?php if ($k == 0) echo 'style="visibility:hidden"'?>
                     />
                </a>
                <a href="<?php if ($k < $this->paginator->getCurrentItemCount()-1) echo $this->url(array('action' => 'move-down', 'id' => $entry['id'])); else echo "#" ?>">
                    <img src="/images/movedown.png" alt="Move Down"
                         <?php if ($k == $this->paginator->getCurrentItemCount() - 1) echo 'style="visibility:hidden"'?>
                     />
                </a>
            </td>
			<td><?php if ($entry['defaultFlag']) echo 'Default'?></td>
			<td><?php echo $this->escape($entry['ami'])?></td>
			<td><?php echo $this->escape($entry['platform'])?></td>
			<td><?php if ($entry['ebsFlag'] == 'Y') echo 'EBS'; else echo 'S3';?></td>
			<td><?php if ($entry['clusterFlag'] == 'Y') echo 'Cluster'; else echo 'Regular';?></td>
			<td><?php if($entry['gpuFlag'] == 'Y') echo 'GPU';?></td>
			<td><?php echo $this->escape($entry['osFamily'])?></td>
            <td class="center">
                <a href="<?php echo $this->url(array('action' => 'delete', 'id' => $entry['id']))?>" onclick="javascript:return confirm('Do you really want delete \'<?php echo $this->escape($entry['type'])?>\'?')" title="Delete Tool">
                    <img src="/images/trash.gif"/>
                </a>
            </td>
        </tr>
		<? endforeach ?>
	</tbody>
    </table>
</div>
