<div class="clear"></div>
<div class="list">
    <?php echo $this->partial('_round_corners.phtml')?>
    <table cellspacing="0" cellpadding="0" border="0">
	<thead>
	<tr>
        <?php
            $columns = array(
               array('column_name' => 'Login ID'),
               array('column_name' => 'Organization'),
               array('column_name' => 'User Name'),
               array('column_name' => 'Email'),
               array('column_name' => 'Active'),
               array('column_name' => 'Active Instances'),
               array('column_name' => 'Last Instances Started'),
               array('column_name' => 'Last Instances Ended'),
               array('column_name' => 'Charged ($)'),
               array('column_name' => 'Remaining ($)'),
            );
            echo $this->partialLoop('_column_header.phtml', $columns);
        ?>
	</tr>
	</thead>
	<tfoot>
        <tr>
            <th colspan="10">
                <?php echo $this->paginator ?>
            </th>
        </tr>
        <tr>
        <th colspan="1">
        <input onmouseover="this.style.backgroundPosition='bottom';" onmouseout="this.style.backgroundPosition='top';"
            id="button_print" class="button_105"
            type="button" value="Print" onclick="window.open('<?php echo $this->url(array('action' => 'list-print'))?>')" />
        </th>
        <th colspan="1">
        <input onmouseover="this.style.backgroundPosition='bottom';" onmouseout="this.style.backgroundPosition='top';"
            id="button_export" class="button_105"
            type="button" value="Export" onclick="window.location='<?php echo $this->url(array('action' => 'list-csv'))?>'" />
        </th>
	    <th colspan="8">
	    <input onmouseover="this.style.backgroundPosition='bottom';" onmouseout="this.style.backgroundPosition='top';"
            id="button_new_dataset" class="button_105"
            type="button" value="Add User" onclick="window.location='<?php echo $this->url(array('action' => 'add'))?>'" />
            </th>
        </tr>
	</tfoot>

    <tbody>
        <?php foreach($this->paginator as $entry): ?>
        <tr>
            <td><a href="<?php echo $this->url(array('action' => 'edit', 'id' => $entry['id']))?>"><?php echo $this->escape($entry['login'])?></a></td>
            <td><a href="/index.php?page=edit_organization&action=<?php echo $this->escape($entry['organization_id'])?>"><?php echo $this->escape($entry['organization'])?></a></td>
            <td><?php echo $this->escape($entry['name'])?></td>
            <td><a href="mailto:<?php echo $this->escape($entry['email'])?>"><?php echo $this->escape($entry['email'])?></a></td>
            <td><?php if ($entry['active'] == 'Y') echo 'Yes'; else echo 'No'?></td>
            <td class="right"><a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'history', 'filter' => $this->currentUser->organization_id.'_'.$entry['id']), 'default', true)?>"><?php echo $this->escape($entry['runningInstCount'])?></a></td>
            <td><?php echo $this->dateFormat($this->escape($entry['lastInstanceStart']))?></td>
            <td><?php echo $this->dateFormat($this->escape($entry['lastInstanceTerminate']))?></td>
            <td class="right"><?php echo number_format($this->escape($entry['totalCharged']))?></td>
            <td class="right"><?php echo number_format($this->escape($entry['remainingLimit']))?></td>
        </tr>
		<? endforeach ?>
	</tbody>
    </table>
</div>
