<div class="list">
    <?php echo $this->partial('_round_corners.phtml')?>
    <table cellspacing="0" cellpadding="0" border="0">
	<thead>
	<tr>
        <?php
            $columns = array(
               array('column_name' => 'Id'),
               array('column_name' => 'Abbr'),
               array('column_name' => 'Name'),
               array('column_name' => 'DB Schema Name'),
            );
            echo $this->partialLoop('_column_header.phtml', $columns);
        ?>
	</tr>
	</thead>
	<tfoot>
        <tr>
            <th colspan="7">
                <?php echo $this->paginator ?>
            </th>
        </tr>
        <tr>
	    <th colspan="7">
	    <input onmouseover="this.style.backgroundPosition='bottom';" onmouseout="this.style.backgroundPosition='top';"
            id="button_new_dataset" class="button_105"
            type="button" value="Add Source" onclick="window.location='<?php echo $this->url(array('action' => 'add'))?>'" />
            </th>
        </tr>
	</tfoot>

    <tbody>
        <?php foreach($this->paginator as $entry):?>
        <tr>
			<td class="right"><?php echo $this->escape($entry['SOURCE_ID'])?></td>
            <td><a href="<?php echo $this->url(array('action' => 'edit', 'id' => $entry['SOURCE_ID']))?>"><?php echo $this->escape($entry['SOURCE_ABBR'])?></a></td>
			<td><?php echo $this->escape($entry['SOURCE_NAME'])?></td>
			<td><?php echo $this->escape($entry['SCHEMA_NAME'])?></td>
       </tr>
		<? endforeach ?>
	</tbody>
    </table>
</div>
