<?php 
/*==============================================================================
    OMOP - Cloud Research Lab

    Observational Medical Outcomes Partnership
    14 Mar 2011

    Page view for loading OSIM2 summary sets.

    (c)2009-2011 Foundation for the National Institutes of Health (FNIH)

    Licensed under the Apache License, Version 2.0 (the "License"); you may not
    use this file except in compliance with the License. You may obtain a copy
    of the License at http://omop.fnih.org/publiclicense.

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. Any
    redistributions of this work or any derivative work or modification based on
    this work should be accompanied by the following source attribution: "This
    work is based on work by the Observational Medical Outcomes Partnership
    (OMOP) and used under license from the FNIH at
    http://omop.fnih.org/publiclicense.

    Any scientific publication that is based on this work should include a
    reference to http://omop.fnih.org.

==============================================================================*/
?>
<?php echo $this->partial(
    '_javascript_autoload.phtml', 
    array('page' => 'loadOsim2Summary')
)?>
<?php $this->headStyle()->captureStart()?>
.list { padding: 10px 0;}
#container form.form2 label { width: 150px; }
<?php $this->headStyle()->captureEnd()?>

<div class="list">
    <?php echo $this->partial('_round_corners.phtml')?>
    <?php $this->form->setAction($this->url()) ?>
    <?php echo $this->form ?>    
</div>
