<?php 
/*==============================================================================
    OMOP - Cloud Research Lab

    Observational Medical Outcomes Partnership
    16 Mar 2011

    Page view for loading OSIM2 summary details.

    (c)2009-2011 Foundation for the National Institutes of Health (FNIH)

    Licensed under the Apache License, Version 2.0 (the "License"); you may not
    use this file except in compliance with the License. You may obtain a copy
    of the License at http://omop.fnih.org/publiclicense.

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. Any
    redistributions of this work or any derivative work or modification based on
    this work should be accompanied by the following source attribution: "This
    work is based on work by the Observational Medical Outcomes Partnership
    (OMOP) and used under license from the FNIH at
    http://omop.fnih.org/publiclicense.

    Any scientific publication that is based on this work should include a
    reference to http://omop.fnih.org.

==============================================================================*/
?>
<?php echo $this->partial(
    '_javascript_autoload.phtml', 
    array('page' => 'osim2SummaryDetails')
)?>
<?php $this->headStyle()->captureStart()?>
#summary-block { margin: 15px 0 15px 10px; }
#summary-block div
{
    width: 850px;
}
#summary-block div .label
{
    width: 130px;
    margin: 4px 10px 0 0;
    float: left;
}
#summary-block div .propertyValue
{
    width: 685px;
    padding: 3px 5px;
    margin: 0;
}
<?php $this->headStyle()->captureEnd()?>

<div class="list" id="osim2-analysis-summary-details">
    <?php echo $this->partial('_round_corners.phtml')?>
    <div id="summary-block">
        <h3>Basic information</h3>
        <div>
            <div class="label">Name</div>        
            <div class="propertyValue">
            <?php echo $this->entity->getName() ?>
            </div>
        </div>
        <div>
            <div class="label">Description</div>        
            <div class="propertyValue">
            <?php echo $this->entity->getDescription() ?>
            </div>
        </div>
        <h3>Data</h3>
    </div>
    <table cellspacing="0" cellpadding="0" border="0">
        <thead>
        <tr>
            <th>Table name</th>
            <th>Rows</th>
            <th style="width:100px;">&nbsp;</th>
        </tr>
        </thead>    
        <tbody>
            <?php
            foreach ($this->tablesData as $data) {
                $table = $data['table'];
                $rowCount = $data['rowCount'];
                $viewUrl =  $this->url(
                    array('action' => 'view-table', 
                        'table' => $table)
                );
                $downloadUrl = $this->url(
                    array('action' => 'download-table', 
                        'table' => $table)
                );
            ?>
            <tr>
                <td><?php echo $table; ?></td>
                <td><?php echo $rowCount; ?></td>
                <td>
                    <a href="<?php echo $viewUrl ?>">View</a>
                    <a href="<?php echo $downloadUrl ?>">Download</a>
                </td>
            </tr>
            <?php 
            } 
            ?>
        </tbody>
    </table>
</div>
