<?php 
/*==============================================================================
    OMOP - Cloud Research Lab

    Observational Medical Outcomes Partnership
    10 Mar 2011

    Page view for displaying list of summary sets.

    (c)2009-2011 Foundation for the National Institutes of Health (FNIH)

    Licensed under the Apache License, Version 2.0 (the "License"); you may not
    use this file except in compliance with the License. You may obtain a copy
    of the License at http://omop.fnih.org/publiclicense.

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. Any
    redistributions of this work or any derivative work or modification based on
    this work should be accompanied by the following source attribution: "This
    work is based on work by the Observational Medical Outcomes Partnership
    (OMOP) and used under license from the FNIH at
    http://omop.fnih.org/publiclicense.

    Any scientific publication that is based on this work should include a
    reference to http://omop.fnih.org.

==============================================================================*/
?>
<?php $this->headStyle()->captureStart()?>
#tableContainer { width: 1120px; overflow:auto; }
#container div.list table {width: 1100px; }
.button_105 { margin: 0px; font: 13px/13px Arial;}
<?php $this->headStyle()->captureEnd()?>
<?php
$postUrl =  $this->url(
    array('controller' => 'osim2','action' => 'view-table'), 
    'default', 
    true
);
?>
<div class="list">
    <?php echo $this->partial('_round_corners.phtml')?>
    <form action="<?php echo $postUrl?>" method="GET" class="form4">
    <fieldset>
        <div>
            <label for="id">Summary Set:</label>
            <?php 
echo $this->formSelect(
    'id', 
    $this->currentId, 
    null, 
    $this->summarySets
); ?>
        </div>
        <div>
            <label for="table">Table:</label>
            <?php 
echo $this->formSelect(
    'table', 
    $this->currentTable, 
    null, 
    $this->availableTables
); ?>
        </div>
&nbsp;
&nbsp;
&nbsp;
        <input onmouseover="this.style.backgroundPosition='bottom';" 
                    onmouseout="this.style.backgroundPosition='top';" 
                    id="button_filter" class="button_80"
                    type="submit" value="Filter" 
                    />
        
&nbsp;
&nbsp;
&nbsp;
        <input onmouseover="this.style.backgroundPosition='bottom';" 
                    onmouseout="this.style.backgroundPosition='top';" 
                    id="button_filter" class="button_80"
                    type="button" value="Download" 
                    onclick="window.location='<?php 
echo $this->url(
    array(
        'action' => 'download-table', 
        'id'=> $this->currentId, 
        'table' => $this->currentTableName)
); ?>'"
                    />
        
&nbsp;
&nbsp;
&nbsp;
        <input onmouseover="this.style.backgroundPosition='bottom';" 
                    onmouseout="this.style.backgroundPosition='top';" 
                    id="button_filter" class="button_105"
                    type="button" value="Download Set" 
                    onclick="window.location='<?php 
echo $this->url(
    array(
        'action' => 'download-summary-set', 
        'id'=> $this->currentId
    )
)
?>'"
                    />
    </fieldset>
</form>
    
    <div id="tableContainer">
    <table cellspacing="0" cellpadding="0" border="0" 
        id="osim2-analysis-summary-table">
        <thead>
        <tr>
            <?php foreach ($this->columns as $columnName) {?>
                <th>
                    <?php echo $this->escape($columnName) ?>
                </th>
            <?php
}
?>
        </tr>
        </thead>
        <tfoot>
            <tr>
                <th colspan="<?php echo count($this->columns) ?>">
                    <?php 
echo $this->paginationControl(
    $this->paginator, 
    null, 
    null, 
    array('urlOptions' => array('id'=>$this->currentId, 
        'table' => $this->currentTable))
); ?>
                </th>
            </tr>
        </tfoot>
        <tbody>
<?php 
foreach ($this->paginator as $entry) {
?>
            <tr>
                <?php
                $i= 0;
                foreach ($entry as $cellData) {
                    $i++;
                    if ($i === 1 || $i == count($entry)) {
                        continue;
                    }
                ?>
                <td style="text-align:right">
                    <?php echo $this->escape($cellData)?>
                </td>
<?php
                }
?>       
            </tr>
<?php 
} 
?>
        </tbody>
    </table>
    </div>
</div>
